### ISSUE TITLE
Help.

### ISSUE THREAD

**Issue by ghost** [AwesomePowered/SpawnTP#12]
https://dev.bukkit.org/bukkit-plugins/spawntp/

I need version to 1.10.2, please!!!

Java 8!

**Comment by blha303** [comment]
I dont know about lax, but my rate is $100 an hour and I haven't done Java for years. You sent a PM for ToggleInventory on dev.bukkit.org as well, I don't know my login for that site so same response there.

**Comment by ghost** [comment]
You will never find a job where you pay $ 100 / hour.

**Comment by blha303** [comment]
I've done freelance work for $100 an hour before, it's not unusual. Regardless, I was mainly answering your PM's from Bukkit as I don't have my login there. If @LaxWasHere is around I'm sure he would be able to help with this plugin if he's not too busy

**Comment by LaxWasHere** [comment]
Uhhh, it still works regardless of Minecraft version? If you're looking for a sound fix, go here https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html

**Comment by ghost** [comment]
Pls help, thanks. I love you, really. T-T
